---
title: "Test lock"
tutorial:
  id: "Test_01"
  version: 0.1
  
output:
  learnr::tutorial:
    progressive: false
    allow_skip: true
runtime: shiny_prerendered
description: >
  Learn the basics of Quarto.
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(ISDSfunctions)
library(gradethis)

gradethis_setup(pass = "Submitted",
                fail = "Submitted",
                error_checker.message = "Submitted",
                fail.hint = FALSE
                )


isds_setup(isds_exam = TRUE)

#exam_seed_ui(id = "seed")

knitr::opts_chunk$set(echo = FALSE)
```

```{r, context = "server-start"}
#exam_seed_server(id = "seed")
```

```{r, context = "server"}
lock_server("lock0")
reset_server("reset", file_name = "example", package_name = "ISDSfunctions")
```

```{r}
exam_output_ui(id = "lock0")
lock_button_ui(id = "lock0")
reset_button_ui(id = "reset")
```


knit_hooks$set lets you create custom code chunk arguments

## Exercises

**Exercise 1:**

A code chunk can be used as a calculator. Try typing 2+2 into the code chunk and running the code.

```{r, context = "render"}
print(rnorm(1))
```


```{r Ex1, exercise = TRUE, exercise.eval = TRUE}

```

```{r Ex1-solution, exercise.reveal_solution = FALSE}
2 + 2
```

```{r Ex1-code-check}
grade_this_code()
```

```{r Q}
exam(
  shuffle = TRUE,
  question("Q1a",
           answer("29"),
           answer("18", correct = TRUE),
           answer("21"),
           allow_retry = TRUE,
           correct = "submitted",
           incorrect = "Submitted",
           random_answer_order = TRUE,
           options = list(multi_part = "a",
                          group = "1")),
  question("Q1b",
           answer("29"),
           answer("18", correct = TRUE),
           answer("21"),
           allow_retry = TRUE,
           correct = "submitted",
           incorrect = "Submitted",
           random_answer_order = TRUE,
           options = list(multi_part = "a")),
  question("Q2",
           answer("29"),
           answer("18", correct = TRUE),
           answer("21"),
           allow_retry = TRUE,
           correct = "submitted",
           incorrect = "Submitted",
           random_answer_order = TRUE),
  question("Q3 option 1",
           answer("29"),
           answer("18", correct = TRUE),
           answer("21"),
           allow_retry = TRUE,
           correct = "submitted",
           incorrect = "Submitted",
           random_answer_order = TRUE,
           options = list(group = "2")),
  question("Q3 option 2",
           answer("29"),
           answer("18", correct = TRUE),
           answer("21"),
           allow_retry = TRUE,
           correct = "submitted",
           incorrect = "Submitted",
           random_answer_order = TRUE,
           options = list(group = "2")),
          question("Q4",
           answer("29"),
           answer("18", correct = TRUE),
           answer("21"),
           allow_retry = TRUE,
           correct = "submitted",
           incorrect = "Submitted",
           random_answer_order = TRUE),
  question("Q5",
           answer("29"),
           answer("18", correct = TRUE),
           answer("21"),
           allow_retry = TRUE,
           correct = "submitted",
           incorrect = "Submitted",
           random_answer_order = TRUE) 
  
)
```



